// Connect actions:
// Pilots
export const FETCH_PILOT_PROJECTS = "FETCH_PILOT_PROJECTS";
export const FETCH_PILOT_PROJECTS_SUCCESS = "FETCH_PILOT_PROJECTS_SUCCESS";

// Topics
export const FETCH_TOPIC_QUESTIONS = "FETCH_TOPIC_QUESTIONS";
export const FETCH_TOPIC_QUESTIONS_SUCCESS = "FETCH_TOPIC_QUESTIONS_SUCCESS";

export const FETCH_TOPIC_ANSWERS = "FETCH_TOPIC_ANSWERS";
export const FETCH_TOPIC_ANSWERS_SUCCESS = "FETCH_TOPIC_ANSWERS_SUCCESS";

