// Connect actions:
// Pilots
export const FETCH_PILOTS_PROJECTS = "FETCH_PILOT_PROJECTS";
export const FETCH_PILOTS_PROJECTS_SUCCESS = "FETCH_PILOT_PROJECTS_SUCCESS";

// Topics
export const FETCH_TOPICS_QUESTIONS = "FETCH_TOPIC_QUESTIONS";
export const FETCH_TOPICS_QUESTIONS_SUCCESS = "FETCH_TOPIC_QUESTIONS_SUCCESS";

export const FETCH_TOPICS_ANSWERS = "FETCH_TOPIC_ANSWERS";
export const FETCH_TOPICS_ANSWERS_SUCCESS = "FETCH_TOPIC_ANSWERS_SUCCESS";


// Resources
export const FETCH_RESOURCES_ARTICLES = "FETCH_RESOURCES_ARTICLES";
export const FETCH_RESOURCES_ARTICLES_SUCCESS = "FETCH_RESOURCES_ARTICLES_SUCCESS";

// Experts
export const FETCH_EXPERTS_PERSONNELS = "FETCH_EXPERTS_PERSONNEL";
export const FETCH_EXPERTS_PERSONNELS_SUCCESS = "FETCH_EXPERTS_PERSONNEL_SUCCESS";


